test/GovernanceOLAS.js

- Adding more governance tests.

test: more governance tests

---

README.md

- Adding a link to the bounty program

doc: adding a link to the bounty program

---

README.md
contracts/GovernorOLAS.sol
contracts/OLAS.sol
contracts/Timelock.sol
contracts/buOLAS.sol
contracts/veOLAS.sol
docs/optimizations.md

- More clarifications to optimizations, potentially incorrectly interpreted code;
- Added comments to frequently encountered false positives.

doc: adding more clarifications to optimizations, code

---

test/buOLAS.js

- Adding a test where `revoke()` is called after the `buOLAS` lock period ends, and `createLockFor()` becomes available in this scenario.

test: add a scenario with revoke after the lock period ends in buOLAS

---

.dockerignore
.github/workflows/workflow.yaml
Dockerfile
README.md

* to support docker to connect frontend locally with the backend

feat: docker image

---

hardhat.config.js

- Changing the default mnemonic such that hardhat shows private keys.

chore: changing the default mnemonic

---

contracts/wveOLAS.sol
test/wGovernanceOLAS.js
test/wveOLAS.js

- Implementing wrapped veOLAS;
- Adding tests;
- Coverage is 100%.

feat and test: implementing wrapped veOLAS

---

README.md
contracts/wveOLAS.sol
hardhat.config.js.fork
package.json
scripts/deployment/README.md
scripts/veCompare/veCompareViewFunctions.js
test/wGovernanceOLAS.js
test/wveOLAS.js

- Adding the rest of view function;
- Adding back tests to have a 100% coverage.

refactor: adding the rest of view functions in veOLAS wrapper

---

README.md
scripts/deployment/bridges/gnosis/README.md

- Updating readme-s in related places.

doc: updating readme

---

abis/0.8.20/GovernorOLAS.json
contracts/GovernorOLAS.sol
contracts/Timelock.sol
hardhat.config.js
package.json
yarn.lock

- Upgrading OpenZeppelin to the version 4.9.1.

refactor: upgrading OpenZeppelin to the version 4.9.1

---

scripts/deployment/deploy_19_revoke_CM.js

Script providing the inputs for CM removal proposal

Create script for CM removal

---

CHANGELOG.md

doc: changelog

---

.solcover.js
contracts/multisigs/GuardCM.sol
contracts/multisigs/test/MockTimelockCM.sol
contracts/multisigs/test/MockTreasury.sol
contracts/test/SafeSetup.sol
hardhat.config.js
test/CM.js
test/GovernanceOLAS.js

- CM guard implementation;
- Added tests.

feat: initial CM guard implementation

---

docs/configuration.json

-  changing configuration file with the Guard CM deployment.

chore: changing configuration file for goerli

---

scripts/proposals/proposal_04_CM_guard.js

- Updating a proposal script for the GuardCM.

chore: updating a proposal script for the GuardCM

---

CHANGELOG.md
audits/README.md
scripts/audit_chains/audit_contracts_setup.js

- added link to the last external audit report
- updated CHANGELOG with v1.1.5 changes
- updated the audit _contract_setup script

Audit-report

---

contracts/multisigs/GuardCM.sol
test/CM.js
test/GuardCM.js

- Extending guard functionality for cross-chain calls.

feat: extending guard functionality for cross-chain calls

---

contracts/VoteWeighting.sol
hardhat.config.js
package.json
test/VoteWeighting.js
yarn.lock

- Accounting for non-EVM chains for vote weighting.

refactor: accounting for non-evm chains for vote weighting

---

scripts/analyzers/code_line_report.txt

final-SoLC

---

docs/configuration.json

- Correcting Burner address in the configuration file.

chore: correcting Burner address in the configuration file

---

scripts/audit_chains/audit_contracts_setup.js
scripts/proposals/proposal_07_voteWeighting_remove_nominees.js

- Static audit update and proposal script.

chore: static audit update and proposal script

---

scripts/deployment/bridges/optimistic/globals_celo_mainnet.json

- Celo globals to default state.

chore: celo globals to default state

---

README.md
docs/flowchart.md
package.json
scripts/audit_chains/audit_contracts_setup.js
scripts/audit_chains/audit_repo_contract.sh
scripts/proposals/proposal_10_update_min_delay.js
yarn.lock

- Doc and flowchart updates.
- Static audit update.

doc: doc update
